=== freedomfractions/EasyAFv3/lib/EasyAF.Export/Output Template Files/EasyPower_Title_Block.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>
			The rules in this schema are used to validate EasyPower One-line Title Block templates.
		</xs:documentation>
	</xs:annotation>
  <!--Units-->
  <xs:simpleType name="units">
    <xs:restriction base="xs:string">
      <xs:enumeration value="inches"/>
      <xs:enumeration value="mm"/>
    </xs:restriction>
  </xs:simpleType>
  <!--Horizontal Alignment-->
	<xs:simpleType name="h_alignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left"/>
			<xs:enumeration value="center"/>
			<xs:enumeration value="right"/>
		</xs:restriction>
	</xs:simpleType>
	<!--Vertical Alignment-->
	<xs:simpleType name="v_alignment">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top"/>
			<xs:enumeration value="center"/>
			<xs:enumeration value="baseline"/>
			<xs:enumeration value="bottom"/>
		</xs:restriction>
	</xs:simpleType>
	<!--Units-->
	<xs:simpleType name="scale">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<!--Color-->
	<xs:simpleType name="color">
		<xs:restriction base="xs:string">
			<xs:pattern value="#((FF)|(ff))((\d)|(A)|(B)|(C)|(D)|(E)|(F)|(a)|(b)|(c)|(d)|(e)|(f)){6}" />
		</xs:restriction>
	</xs:simpleType>
	<!--Font Sizes-->
	<xs:simpleType name="font_size">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="3" />
			<xs:maxInclusive value="100" />
		</xs:restriction>
	</xs:simpleType>
	<!--Font Escapement-->
	<xs:simpleType name="font_escapement">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="3600" />
		</xs:restriction>
	</xs:simpleType>
	<!--Line Width-->
	<xs:simpleType name="line_width">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="6" />
		</xs:restriction>
	</xs:simpleType>
	<!--Line Styles-->
	<xs:simpleType name="line_style">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0" />
			<xs:enumeration value="1" />
			<xs:enumeration value="2" />
			<xs:enumeration value="3" />
			<xs:enumeration value="4" />
		</xs:restriction>
	</xs:simpleType>
	<!--Root-->
	<xs:element name="TitleBlock">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" name="Settings" >
					<xs:complexType>
						<xs:all>
							<xs:element minOccurs="0" maxOccurs="1" name="Scale" type="scale" />
              <xs:element minOccurs="0" maxOccurs="1" name="Units" type="units" />
              <xs:element minOccurs="0" maxOccurs="1" name="BorderWidth" type="xs:integer" />
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:choice maxOccurs="unbounded">
					<xs:element minOccurs="0" maxOccurs="unbounded" name="Text">
						<xs:complexType>
							<xs:sequence>
								<xs:choice maxOccurs="unbounded">
									<xs:element minOccurs="0" maxOccurs="1" name="X" type="xs:decimal" />
									<xs:element minOccurs="0" maxOccurs="1" name="Y" type="xs:decimal" />
									<xs:element minOccurs="0" maxOccurs="1" name="VAlign" type="v_alignment" />
									<xs:element minOccurs="0" maxOccurs="1" name="HAlign" type="h_alignment" />
									<xs:element minOccurs="1" maxOccurs="1" name="Prompt" type="xs:string" />
									<xs:element minOccurs="1" maxOccurs="1" name="Label" type="xs:string" />
									<xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
									<xs:element minOccurs="1" maxOccurs="1" name="FontName" type="xs:string" />
									<xs:element minOccurs="1" maxOccurs="1" name="FontSize" type="font_size" />
									<xs:element minOccurs="1" maxOccurs="1" name="Escapement" type="font_escapement" />
									<xs:element minOccurs="1" maxOccurs="1" name="Bold" type="xs:boolean" />
									<xs:element minOccurs="1" maxOccurs="1" name="Italic" type="xs:boolean" />
									<xs:element minOccurs="1" maxOccurs="1" name="Color" type="color" />
								</xs:choice>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="Rect">
						<xs:complexType>
							<xs:sequence>
								<xs:choice maxOccurs="unbounded">
									<xs:element minOccurs="1" maxOccurs="1" name="left" type="xs:decimal" />
									<xs:element minOccurs="1" maxOccurs="1" name="top" type="xs:decimal" />
									<xs:element minOccurs="1" maxOccurs="1" name="right" type="xs:decimal" />
									<xs:element minOccurs="1" maxOccurs="1" name="bottom" type="xs:decimal" />
									<xs:element minOccurs="0" maxOccurs="1" name="LineWidth" type="line_width" />
									<xs:element minOccurs="0" maxOccurs="1" name="Color" type="color" />
								</xs:choice>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="Image">
						<xs:complexType>
							<xs:all>
								<xs:element minOccurs="1" maxOccurs="1" name="left" type="xs:decimal" />
								<xs:element minOccurs="1" maxOccurs="1" name="top" type="xs:decimal" />
								<xs:element minOccurs="1" maxOccurs="1" name="right" type="xs:decimal" />
								<xs:element minOccurs="1" maxOccurs="1" name="bottom" type="xs:decimal" />
								<xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
								<xs:element minOccurs="0" maxOccurs="1" name="Prompt" type="xs:string" />
								<xs:element minOccurs="0" maxOccurs="1" name="File" type="xs:string" />
								<xs:element minOccurs="0" maxOccurs="1" name="Color" type="color" />
							</xs:all>
						</xs:complexType>
					</xs:element>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="Line">
						<xs:complexType>
							<xs:all>
								<xs:element minOccurs="1" maxOccurs="1" name="X1" type="xs:decimal" />
								<xs:element minOccurs="1" maxOccurs="1" name="Y1" type="xs:decimal" />
								<xs:element minOccurs="1" maxOccurs="1" name="X2" type="xs:decimal" />
								<xs:element minOccurs="1" maxOccurs="1" name="Y2" type="xs:decimal" />
								<xs:element minOccurs="0" maxOccurs="1" name="LineWidth" type="xs:integer" />
								<xs:element minOccurs="0" maxOccurs="1" name="LineStyle" type="line_style" />
								<xs:element minOccurs="0" maxOccurs="1" name="Color" type="color" />
							</xs:all>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== freedomfractions/EasyAFv3/lib/EasyAF.Export/Output Template Files/TitleBlockTemplate.xml
<?xml version="1.0" encoding="utf-8" ?>
<TitleBlock xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EasyPower_Title_Block.xsd">
  <!-- comment-->
  <Settings>
    <Scale>0</Scale>
    <BorderWidth>1</BorderWidth>
  </Settings>
  <!-- border linework -->
  <Rect> <!-- border rect -->
    <left>0.5</left>
    <top>0.5</top>
    <right>35.5</right>
    <bottom>23.5</bottom>
    <LineWidth>2</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Rect>
    <!-- sheet no rect -->
    <left>34.6875</left>
    <top>22.6875</top>
    <right>35.5</right>
    <bottom>23.5</bottom>
    <LineWidth>1</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Text>
    <!-- Sheet No Title text -->
    <X>34.7969</X>
    <Y>22.875</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>SHEET NO.</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- 'Drawing No.' text prompt -->
    <X>35.0937</X>
    <Y>22.925</Y>
    <Alignment>6</Alignment>
    <Color>#FF000000</Color>
    <Label>%DrawingName%</Label>
    <FontName>Arial Narrow</FontName>
    <FontSize>26</FontSize>
  </Text>
  <Rect>
    <!-- sheet of sheets rect -->
    <left>32.4766</left>
    <top>22.6875</top>
    <right>35.5</right>
    <bottom>23.5</bottom>
    <LineWidth>1</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Text>
    <!-- 'SHEET' text -->
    <X>32.5312</X>
    <Y>22.875</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>SHEET</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- SHEET NO text prompt -->
    <Prompt>Sheet No.</Prompt>
    <Name>Sheet No.</Name>
    <X>33.1</X>
    <Y>22.875</Y>
    <Alignment>14</Alignment>
    <Color>#FF000000</Color>
    <Label>1</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- 'OF' text -->
    <X>33.4727</X>
    <Y>22.875</Y>
    <Alignment>14</Alignment>
    <Color>#FF000000</Color>
    <Label>OF</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- SHEET COUNT text prompt -->
    <Prompt>Sheet Count</Prompt>
    <Name>Sheet Count</Name>
    <X>33.8906</X>
    <Y>22.875</Y>
    <Alignment>14</Alignment>
    <Color>#FF000000</Color>
    <Label>40</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- 'SHEETS' text -->
    <X>34.1797</X>
    <Y>22.875</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>SHEETS</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Line>
    <!-- att dwg no horz divider -->
    <X1>32.4766</X1>
    <Y1>22.9375</Y1>
    <X2>34.6875</X2>
    <Y2>22.9375</Y2>
    <LineWidth>1</LineWidth>
    <Color>0</Color>
  </Line>
  <Text>
    <!-- 'AT&T DRAWING NO.' text -->
    <X>32.5235</X>
    <Y>23.0875</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>AT&amp;T DRAWING NO.:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- ATT Drawing No text prompt -->
    <Prompt>ATT Drawing No</Prompt>
    <Name>ATT Drawing No</Name>
    <X>33.582</X>
    <Y>23.2187</Y>
    <Alignment>0</Alignment>
    <Color>#FF000000</Color>
    <Label></Label>
    <FontName>Arial</FontName>
    <FontSize>10</FontSize>
  </Text>
  <Rect>
    <!-- att proj no rect -->
    <left>30.543</left>
    <top>22.1875</top>
    <right>32.4766</right>
    <bottom>22.6875</bottom>
    <LineWidth>1</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Text>
    <!-- 'AT&T Project No' text -->
    <X>30.5703</X>
    <Y>22.3375</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>AT&amp;T PROJECT NUMBER:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- ATT Project No text prompt -->
    <Prompt>ATT Project No</Prompt>
    <Name>ATT Project No</Name>
    <X>30.5942</X>
    <Y>22.625</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>__ATT_PROJ_NO__</Label> <!-- PROJECT RELATED TAG -->
    <FontName>Arial</FontName>
    <FontSize>10</FontSize>
  </Text>
  <Rect>
    <!-- att auth rect -->
    <left>30.543</left>
    <top>22.6875</top>
    <right>32.4766</right>
    <bottom>23.5</bottom>
    <LineWidth>1</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Text>
    <!-- 'AT&T AUTHORIZATION' text -->
    <X>30.5703</X>
    <Y>22.8375</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>AT&amp;T AUTHORIZATION:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Line>
    <!-- att auth underline -->
    <X1>30.6016</X1>
    <Y1>23.2812</Y1>
    <X2>32.3516</X2>
    <Y2>23.2812</Y2>
    <LineWidth>1</LineWidth>
    <Color>0</Color>
  </Line>
  <Text>
    <!-- ATT PM text prompt -->
    <Prompt>ATT Project Mgr</Prompt>
    <Name>ATT Project Mgr</Name>
    <X>30.5942</X>
    <Y>23.2787</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>TIM BRUNS</Label>
    <FontName>Arial</FontName>
    <FontSize>10</FontSize>
  </Text>
  <Rect>
    <!-- date, scale, drawn by, checked by rect -->
    <left>32.4766</left>
    <top>22.1875</top>
    <right>35.5</right>
    <bottom>22.6875</bottom>
    <LineWidth>1</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Line>
    <!-- date/drawn by horz divider -->
    <X1>32.4766</X1>
    <Y1>22.4375</Y1>
    <X2>35.5</X2>
    <Y2>22.4375</Y2>
    <LineWidth>1</LineWidth>
    <Color>0</Color>
  </Line>
  <Line>
    <!-- date/drawn by vert divider -->
    <X1>33.9883</X1>
    <Y1>22.1875</Y1>
    <X2>33.9883</X2>
    <Y2>22.6875</Y2>
    <LineWidth>1</LineWidth>
    <Color>0</Color>
  </Line>
  <Text>
    <!-- 'DATE' text -->
    <X>32.5039</X>
    <Y>22.375</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>DATE:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- Drawing date text prompt -->
    <Prompt>Drawing Date</Prompt>
    <Name>Drawing Date</Name>
    <X>33.0039</X>
    <Y>22.4</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>__STUDY_DATE__</Label>  <!-- PROJECT RELATED TAG -->
    <FontName>Arial</FontName>
    <FontSize>10</FontSize>
  </Text>
  <Text>
    <!-- 'DRAWN BY' text -->
    <X>32.5039</X>
    <Y>22.625</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>DRAWN BY:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- Drawn by text prompt -->
    <Prompt>Drawn By</Prompt>
    <Name>Drawn By</Name>
    <X>33.2039</X>
    <Y>22.65</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>BPB</Label>
    <FontName>Arial</FontName>
    <FontSize>10</FontSize>
  </Text>
  <Text>
    <!-- 'SCALE' text -->
    <X>34.0156</X>
    <Y>22.375</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>SCALE:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- Scale text prompt -->
    <Prompt>Scale</Prompt>
    <Name>Scale</Name>
    <X>34.5156</X>
    <Y>22.4</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>N.T.S.</Label>
    <FontName>Arial</FontName>
    <FontSize>10</FontSize>
  </Text>
  <Text>
    <!-- 'CHECKED BY' text -->
    <X>34.0156</X>
    <Y>22.625</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>CHECKED BY:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- Checked by text prompt -->
    <Prompt>Checked By</Prompt>
    <Name>Checked By</Name>
    <X>34.8756</X>
    <Y>22.65</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>MBB</Label>
    <FontName>Arial</FontName>
    <FontSize>10</FontSize>
  </Text>
  <Rect>
    <!-- sheet title rect -->
    <left>30.543</left>
    <top>21.3477</top>
    <right>35.5</right>
    <bottom>22.1875</bottom>
    <LineWidth>1</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Text>
    <!-- 'SHEET TITLE' text -->
    <X>30.5703</X>
    <Y>21.4977</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>SHEET TITLE:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- Sheet Title Line 1 text prompt -->
    <Prompt>Sheet Title 1</Prompt>
    <Name>Sheet Title 1</Name>
    <X>33.0215</X>
    <Y>21.5</Y>
    <Alignment>6</Alignment>
    <Color>#FF000000</Color>
    <Label>EASYPOWER</Label>
    <FontName>Arial</FontName>
    <FontSize>24</FontSize>
  </Text>
  <Text>
    <!-- Sheet Title Line 2 text prompt -->
    <Prompt>Sheet Title 2</Prompt>
    <Name>Sheet Title 2</Name>
    <X>33.0215</X>
    <Y>21.8</Y>
    <Alignment>6</Alignment>
    <Color>#FF000000</Color>
    <Label>ONE-LINE DIAGRAM</Label>
    <FontName>Arial</FontName>
    <FontSize>24</FontSize>
  </Text>
  <Rect>
    <!-- project info/title rect -->
    <left>30.543</left>
    <top>19.2617</top>
    <right>35.5</right>
    <bottom>21.3477</bottom>
    <LineWidth>1</LineWidth>
    <Color>#FF000000</Color>
  </Rect>
  <Text>
    <!-- 'PROJECT TITLE' text -->
    <X>30.5703</X>
    <Y>19.4117</Y>
    <Alignment>8</Alignment>
    <Color>#FF000000</Color>
    <Label>PROJECT TITLE:</Label>
    <FontName>Arial</FontName>
    <FontSize>8</FontSize>
  </Text>
  <Text>
    <!-- Project Title 1 text prompt -->
    <Prompt>Project Title 1</Prompt>
    <Name>Project Title 1</Name>
    <X>33.0215</X>
    <Y>19.4117</Y>
    <Alignment>6</Alignment>
    <Color>#FF000000</Color>
    <Label>__CLIENT__</Label>  <!-- PROJECT RELATED TAG -->
    <FontName>Arial</FontName>
    <FontSize>22</FontSize>
  </Text>
  <Text>
    <!-- Project Title 2 text prompt -->
    <Prompt>Project Title 2</Prompt>
    <Name>Project Title 2</Name>
    <X>33.0215</X>
    <Y>19.7117</Y>
    <Alignment>6</Alignment>
    <Color>#FF000000</Color>
    <Label>ARC FLASH</Label>
    <FontName>Arial</FontName>
